var express = require("express");
const auth = require("../middleware/auth");
// const authenticateJWT = require("../helper/helper").authenticateJWT;
const AuthController = require("../controller/admincontroller/Api/AuthController");
const CmsController = require("../controller/admincontroller/Api/CmsController");
const UserController = require("../controller/admincontroller/Api/UserController");
const ChangepasswprdController = require("../controller/admincontroller/Api/ChangepasswprdController");
const NotificationController = require("../controller/admincontroller/Api/NotificationController");
const logpackageController = require("../controller/admincontroller/Api/logpackageController");
const ContactController = require("../controller/admincontroller/Api/ContactController");
const RewardController = require("../controller/admincontroller/Api/RewardController");
const RatingController = require("../controller/admincontroller/Api/RatingController");
const TransactionController = require("../controller/admincontroller/Api/TransactionController");

var router = express.Router();
module.exports = (io) => {
  router.get("/adminhistory", UserController.adminhistory);
  router.post("/signup", AuthController.signup);
  router.post("/signin", AuthController.signin);
  router.post("/verifyotp", AuthController.verifyotp);
  router.post("/otpresend", AuthController.otpresend);
  router.get("/cms", CmsController.cms);
  router.post("/forgotPassword", ChangepasswprdController.forgotPassword);
  router.get( "/resetPassword/:id/:ran_token", ChangepasswprdController.resetPassword );
  router.post("/updateForgotPassword",ChangepasswprdController.updateForgotPassword);
  router.get("/sucessmsg", ChangepasswprdController.sucessmsg);
  router.get("/linkExpired", ChangepasswprdController.linkExpired);
  router.use(auth.authenticateJWT);
  router.get("/getprofile", UserController.getprofile);
  router.post("/userupdate", UserController.userupdate);
  router.post("/notificationStatus", AuthController.notificationStatus);
  router.post("/changePassword", ChangepasswprdController.changePassword);
  router.get("/notificationListing", NotificationController.notificationListing);
  router.post("/notification_readstatus", NotificationController.notification_readstatus );
  router.post("/logpackage", logpackageController.logpackage(io));
  router.get("/logpackagedetail", logpackageController.logpackagedetail);
  router.get("/user_logpackagedetail", logpackageController.user_logpackagedetail);
  router.get("/logpackageout", logpackageController.logpackageout);
  router.get("/getcarrier", logpackageController.getcarrier);
  router.get("/homedetail", logpackageController.homedetail);
  router.post("/deliver_package", logpackageController.deliver_package(io));
  router.post("/pointredemrequst", logpackageController.pointredemrequst(io));
  router.post("/redeem_points", logpackageController.redeem_points);
  router.get("/requstlist", logpackageController.requstlist);
  // router.post("/addsupport", ContactController.addsupport);
  router.post("/contactupdate", UserController.contactupdate);
  router.get("/userlisting", UserController.userlisting);
  router.post("/adduser", UserController.adduser);
  router.post("/aprovalstatus", UserController.aprovalstatus);
  router.post("/my_status", UserController.my_status);
  router.get("/rewardlisting", RewardController.rewardlisting);
  router.post("/addreward", RewardController.addreward);
  router.post("/user_delete", UserController.user_delete);
  router.get("/getadminprofile", UserController.getadminprofile);
  router.post("/adminupdate", UserController.adminupdate);
  router.post("/addrating", RatingController.addrating);
  router.get("/ratingdetail", RatingController.ratingdetail);
  router.get("/transactiondetail", TransactionController.transactiondetail);
  router.get("/redeemhistory", TransactionController.redeemhistory);
  router.post("/fileUpload", RatingController.fileUpload);
  router.post("/logout", AuthController.logout);

  return router;
};
